### ISSUE TITLE
Package 'TScompare' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by statmath-it** [cran-task-views/Databases#23]
Package [TScompare](https://CRAN.R-project.org/package=TScompare) is currently listed in CRAN Task View [Databases](https://CRAN.R-project.org/view=Databases) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by coatless** [comment]
Thanks for the heads up. Looks like the last time TScompare was updated on CRAN was back in 2015. 

Check was failing due to: 

```
    tfDetails: no visible global function definition for 'start'
    tfDetails: no visible global function definition for 'end'
    Undefined global functions or variables:
     end start
    Consider adding
     importFrom("stats", "end", "start")
    to your NAMESPACE file.
```

Moreover, one other `TS*` packages [{TSframe} was archived on 2022-05-12 at maintainer's request.](https://cran.r-project.org/web/packages/TSfame/index.html).

So, I'm voting to remove `TScompare` from the task view.

Any objection @terrytangyuan?

**Comment by terrytangyuan** [comment]
Yes we can remove it.
